### ISSUE TITLE
Is Klov available for C# ?

### ISSUE THREAD

**Issue by sathishkumarmani-cesltd** [anshooarora/klovv#21]
Hi @anshooarora,

Is Klov available for C#? If yes, please guide with step by step configuration details.

Thanks

**Comment by anshooarora** [comment]
Only for the professional version. Support for community will be added soon.

**Comment by anshooarora** [comment]
Version 3,1.0 community adds this.

**Comment by appuCES** [comment]
Hi @anshooarora  can we please have full documentation for Klov with C-Sharp on [extentreports.com](http://extentreports.com) ?
